name = "OMOPCDMPathways"
uuid = "413b2380-0cee-426e-ad22-874d5a2600da"
authors = ["Jay-sanjay <landgejay124@gmail.com> and contributors"]
version = "0.0.1"

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FunSQL = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
OMOPCDMCohortCreator = "f525a15e-a73f-4eef-870f-f901257eae22"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
DataFrames = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
