name = "OMOPCDMPathways"
uuid = "413b2380-0cee-426e-ad22-874d5a2600da"
authors = ["Jay-sanjay <landgejay124@gmail.com> and contributors"]
version = "0.0.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"

[compat]
LiveServer = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
